services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/total_recall_api
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
